### PR TITLE
docs: colocate app docs

### PR DESCRIPTION
**Pull request by varl**
Other PRs depend on this one:

- https://github.com/dhis2/dhis2-docs/pull/819
- https://github.com/dhis2/dhis2-docs-builder/pull/49

### CODE REVIEW

**Review by mediremi — APPROVED** [review]

**Comment by Mohammer5** [comment]
Are we planning to add our standard docs setup to this repo as well? Or do we just keep the files in the `docs` folder? If the former is the case, we could add it to this PR, right?

**Comment by varl** [comment]
@Mohammer5 I'm not sure what you mean by standard docs setup ?

**Comment by Mohammer5** [comment]
@varl I meant using `d2-utils-docsite`

**Comment by mediremi** [comment]
@Mohammer5 these docs are for https://docs.dhis2.org/en/home.html, which uses https://www.mkdocs.org/ instead of `d2-utils-docsite`

**Review by Mohammer5 — APPROVED** [review]
ah, I see :ok:

**Pull request merged**
