### PR TITLE
Angularjs i18next

### PR DESCRIPTION
**Pull request by joaoantunes87**

### CODE REVIEW

**Comment by abyot** [comment]
great move to i18next... do you have plans to migrate other apps as well?

**Comment by joaoantunes87** [comment]
Hi, 
I have been integrating other apps, but for future plans it is better to talk with Jason.

**Comment by jason-p-pickering** [comment]
@abyot I think the plan is to try and move all apps to this framework. @joaoantunes87 is working out the best way with both React and Angular apps, and we will present some more detailed findings to the dev team soon. This was a quite easy app to start with, so if things look good, please go ahead and merge it. Otherwise, if you have questions let us know!

**Comment by abyot** [comment]
This is a very old app which I always wanted to refactor but didn't get the time... so we can go ahead and do some experimentation.

**Pull request merged**
